use lss_curso;

select * from peca;

select current_timestamp;

select GETDATE();

SELECT CONVERT(VARCHAR,GETDATE(),103);

SELECT CONVERT(VARCHAR,GETDATE(),109);

SELECT ANO = DATEPART(YEAR,GETDATE()), MÊS = DATEPART (MONTH,GETDATE()), 
	DIA = DATEPART (DAY,GETDATE()), 'DIA DO ANO' = DATEPART (DAYOFYEAR,GETDATE()),
	'DIA DA SEMANA' = DATEPART (WEEKDAY,GETDATE());
	
SELECT CONVERT(VARCHAR,DT_AQUISICAO,103),CD_PECA,NM_PECA FROM PECA;

SELECT CD_PECA, NM_PECA, VALOR_PECA FROM PECA;

SELECT CD_PECA AS 'CÓDIGO DA PEÇA', NM_PECA AS 'NOME DA PEÇA', 
								VALOR_PECA AS 'VALOR' FROM PECA;
--

/* COLOCAR NA CRIAÇÃO DA TABELA COISAS TIPO:

NM_ALUNO VARCHAR(40) NM_ALUNO LIKE '[A-Z]%'
DESSA FORMA, NÃO É POSSÍVEL INSERIR UM ALUNO COM A PRIMEIRA LETRA SENDO 'ESPAÇO' */

